export interface SeasonalPhase {
  month: string;
  stage: string;
  activity: string;
  temperature?: string;
  rainfall?: string;
  irrigation?: string;
  fertilizer?: string;
  pestControl?: string;
  soilPrep?: string;
  seedVariety?: string;
  yield?: string;
  notes?: string;
}

export const seasonalPlans: Record<string, SeasonalPhase[]> = {
  /* ================= RICE ================= */
  rice: [
    {
      month: 'May-June',
      stage: 'Nursery Preparation',
      activity: 'Prepare nursery beds; soak seeds for 24h; treat with fungicide',
      temperature: '25-30°C',
      rainfall: '100-150 mm',
      soilPrep: 'Well-puddled soil, organic matter rich',
      seedVariety: 'IR64, Basmati, PR123 @ 30-40 kg/ha',
      notes: 'Use 1:4 ratio for main field to nursery',
    },
    {
      month: 'June-July',
      stage: 'Transplanting',
      activity: 'Transplant 30-day-old seedlings; maintain 15 cm spacing',
      temperature: '28-32°C',
      rainfall: '150-200 mm',
      irrigation: 'Keep 5 cm standing water; 3-4 irrigations',
      fertilizer: 'DAP 50 kg/ha at transplanting',
      notes: 'Transplant 4-5 seedlings per hill',
    },
    {
      month: 'July-August',
      stage: 'Vegetative Growth',
      activity: 'Apply nitrogen in 2-3 splits; control weeds manually',
      temperature: '28-32°C',
      rainfall: '200-300 mm',
      irrigation: '5-7 cm water depth maintenance',
      fertilizer: 'Urea 50+50 kg/ha at 30 & 45 DAS',
      pestControl: 'Monitor for stem borer, brown planthopper',
      notes: 'First weeding at 20-25 DAS',
    },
    {
      month: 'August-September',
      stage: 'Tiller Formation',
      activity: 'Optimize tiller development; monitor pests closely',
      temperature: '25-30°C',
      rainfall: '150-200 mm',
      irrigation: '5 cm water depth',
      fertilizer: 'Potash 40 kg/ha for grain quality',
      pestControl: 'Apply insecticide for brown planthopper, leaf folder',
      notes: 'Use pheromone traps for pest monitoring',
    },
    {
      month: 'September-October',
      stage: 'Panicle Initiation & Flowering',
      activity: 'Reduce water stress; monitor for diseases; prevent lodging',
      temperature: '24-28°C',
      rainfall: '100-150 mm',
      irrigation: 'Reduce to 2-3 cm water, dry spell 10-12 days',
      pestControl: 'Spray for sheath blight; watch for blast disease',
      notes: 'Critical water management phase; avoid water stress',
    },
    {
      month: 'October-November',
      stage: 'Grain Filling & Maturity',
      activity: 'Maintain water 2-3 cm; monitor for diseases; prepare for harvest',
      temperature: '20-25°C',
      rainfall: '50-75 mm',
      irrigation: 'Reduce frequency; drain 7-10 days before harvest',
      yield: '50-60 quintals/ha with proper management',
      notes: 'Grain maturity in 45-50 days from flowering',
    },
    {
      month: 'November-December',
      stage: 'Harvesting & Post-Harvest',
      activity: 'Harvest at 80% grain maturity; dry to 12-14% moisture',
      temperature: '18-22°C',
      yield: '50-60 quintals/ha paddy, 33-40 quintals/ha rice',
      notes: 'Store in cool, dry place; use improved thresher to reduce loss',
    },
  ],

  /* ================= WHEAT ================= */
  wheat: [
    {
      month: 'September-October',
      stage: 'Land Preparation',
      activity: 'Deep ploughing; incorporate crop residues; level field',
      temperature: '25-30°C',
      rainfall: '0-50 mm',
      soilPrep: 'Remove weeds; ensure proper drainage',
      notes: 'Prepare 2-3 weeks before sowing for soil settling',
    },
    {
      month: 'October-November',
      stage: 'Sowing',
      activity: 'Sow at 100-125 kg/ha; maintain 20 cm row spacing',
      temperature: '15-20°C',
      seedVariety: 'HD2967, WH147, PBW343 @ 100-125 kg/ha',
      irrigation: 'Germination irrigation immediately after sowing',
      fertilizer: 'DAP 50 kg/ha + FYM 5-10 tons/ha',
      notes: 'Sowing window: Oct 25 - Nov 15 for optimal yield',
    },
    {
      month: 'November-December',
      stage: 'Establishment & CRI Stage',
      activity: 'Control weeds; monitor for diseases; irrigation scheduling',
      temperature: '12-18°C',
      rainfall: '25-50 mm',
      irrigation: 'CRI (Crown Root Initiation) irrigation at 20-21 DAS',
      fertilizer: 'Basal: DAP 50 kg/ha; Urea 60 kg/ha before CRI',
      pestControl: 'Monitor for armyworm, cutworm',
      notes: '1st weeding at 30-35 DAS; 2nd at 50-55 DAS',
    },
    {
      month: 'December-January',
      stage: 'Tillering & Stem Elongation',
      activity: 'Apply nitrogen in splits; control broadleaf weeds',
      temperature: '8-15°C',
      rainfall: '10-30 mm',
      irrigation: 'Tillers irrigation at 40-45 DAS; Jointing irrigation at 60 DAS',
      fertilizer: 'Urea 30 kg/ha at Tillers, 30 kg/ha at Jointing stage',
      pestControl: 'Use herbicide for weed control (post-emergence)',
      notes: 'Total 60 kg N/ha for optimum yield',
    },
    {
      month: 'January-February',
      stage: 'Jointing & Ear Emergence',
      activity: 'Final weed removal; monitor for Karnal bunt & loose smut',
      temperature: '10-18°C',
      rainfall: '20-40 mm',
      irrigation: 'Boot stage irrigation at 75-80 DAS',
      pestControl: 'Spray fungicide for rust diseases if required',
      notes: 'Critical for grain number formation',
    },
    {
      month: 'February-March',
      stage: 'Flowering & Grain Filling',
      activity: 'Monitor grain development; prevent water stress',
      temperature: '18-25°C',
      rainfall: '30-50 mm',
      irrigation: 'Grain filling irrigation at 95-100 DAS',
      yield: '45-55 quintals/ha with proper management',
      notes: 'Avoid water stress; grazing/cutting not recommended',
    },
    {
      month: 'March-April',
      stage: 'Maturity & Harvesting',
      activity: 'Harvest at 12-13% moisture; use combine harvester',
      temperature: '25-30°C',
      yield: '45-55 quintals/ha',
      notes: 'Harvest by late April to allow timely preparation for monsoon crops',
    },
  ],

  /* ================= MAIZE ================= */
  maize: [
    {
      month: 'April-May',
      stage: 'Land Preparation & Sowing',
      activity: '2-3 ploughings; create 60 cm rows; sow @ 20 kg/ha',
      temperature: '20-25°C',
      rainfall: '75-100 mm',
      seedVariety: 'NK6240, Pioneer 30G87 @ 18-20 kg/ha',
      fertilizer: 'FYM 10 tons/ha; DAP 50 kg/ha',
      soilPrep: 'Well-drained soil; field slope <1%',
    },
    {
      month: 'May-June',
      stage: 'Seedling & Early Growth',
      activity: 'Thin to 60 cm x 25 cm; apply herbicide for weed control',
      temperature: '22-28°C',
      rainfall: '100-150 mm',
      irrigation: 'First irrigation at 20-25 DAS (Knee High stage)',
      fertilizer: 'Urea 50 kg/ha at V4-V6 stage (thinning)',
      pestControl: 'Monitor for cutworm, armyworm',
    },
    {
      month: 'June-July',
      stage: 'Vegetative Growth',
      activity: 'Maintain plant population; control weeds; 2nd fertilizer split',
      temperature: '25-30°C',
      rainfall: '150-200 mm',
      irrigation: 'Second irrigation at 40-45 DAS (V8 stage)',
      fertilizer: 'Urea 50 kg/ha; Potash 40 kg/ha',
      notes: 'Monitor for fall armyworm using pheromone traps',
    },
    {
      month: 'July-August',
      stage: 'Tasseling & Silking',
      activity: 'Critical irrigation & nutrient stage; prevent stress',
      temperature: '26-32°C',
      rainfall: '150-200 mm',
      irrigation: 'Critical: 3rd irrigation at 60-70 DAS (V10-V12)',
      fertilizer: 'Foliar spray of micronutrients if deficiency symptoms',
      pestControl: 'Monitor for corn borer, cutworm; spray Bt if needed',
      notes: 'Most critical stage for grain formation',
    },
    {
      month: 'August-September',
      stage: 'Grain Filling',
      activity: 'Maintain moisture; monitor for diseases; remove damaged ears',
      temperature: '25-28°C',
      rainfall: '100-150 mm',
      irrigation: '4th irrigation at 80-90 DAS if dry spell',
      pestControl: 'Monitor for diseases: blight, rust, root rot',
      notes: 'Avoid water stress during this critical period',
    },
    {
      month: 'September-October',
      stage: 'Maturity & Drying',
      activity: 'Monitor grain moisture; plan for harvest',
      temperature: '20-25°C',
      rainfall: '25-50 mm',
      yield: '60-80 quintals/ha grain; 150-200 quintals/ha fodder',
      notes: 'Harvest when grain moisture is 20-25%',
    },
    {
      month: 'October-November',
      stage: 'Harvesting & Post-Harvest',
      activity: 'Harvest mature corn; dry to 12-13% moisture for storage',
      temperature: '18-25°C',
      yield: '60-80 quintals/ha',
      notes: 'Use mechanical picker-sheller for efficiency; Store in cool, dry place',
    },
  ],

  /* ================= COTTON ================= */
  cotton: [
    {
      month: 'April-May',
      stage: 'Land Preparation',
      activity: 'Summer ploughing; create 120 cm ridges; incorporate FYM',
      temperature: '30-35°C',
      rainfall: '0-25 mm',
      soilPrep: 'Well-drained soil; ridges 120 cm apart',
      notes: '3-4 ploughings for cotton cultivation',
    },
    {
      month: 'May-June',
      stage: 'Sowing',
      activity: 'Sow @ 15-20 kg/ha on ridges; treat seed with insecticide',
      temperature: '25-30°C',
      rainfall: '50-100 mm',
      seedVariety: 'H4, MCU5, Bt Cotton (Nuziveedhak, Mahyco) @ 15-20 kg/ha',
      irrigation: 'Light irrigation immediately after sowing',
      fertilizer: 'DAP 50 kg/ha; FYM 5 tons/ha',
    },
    {
      month: 'June-July',
      stage: 'Seedling & Thinning',
      activity: 'Thin to 60 cm spacing; gap filling; first weeding',
      temperature: '25-30°C',
      rainfall: '100-150 mm',
      irrigation: 'Light irrigation if soil moisture is low',
      fertilizer: 'Basal dose of N:P:K = 100:50:50 kg/ha',
      notes: 'Thinning should be done at 4-5 leaf stage',
    },
    {
      month: 'July-August',
      stage: 'Vegetative Growth',
      activity: 'Frequent weeding; apply fertilizer in splits; monitor pests',
      temperature: '28-32°C',
      rainfall: '150-200 mm',
      irrigation: 'Regular irrigation at 7-10 day intervals',
      fertilizer: 'Urea 50 kg/ha; apply in 2 splits at 45 & 90 DAS',
      pestControl: 'Monitor for jassid, thrips, spider mites; use neem oil spray',
      notes: '3-4 hoeing and weeding cycles',
    },
    {
      month: 'August-September',
      stage: 'Flowering & Early Boll Formation',
      activity: 'Regulate nitrogen; prevent excessive vegetative growth',
      temperature: '28-30°C',
      rainfall: '100-150 mm',
      irrigation: 'Regular irrigation; avoid waterlogging',
      fertilizer: 'Potash 40 kg/ha for quality; reduce N application',
      pestControl: 'Spray for bollworm: Bt or synthetic pyrethroids',
      notes: 'Remove terminal shoots if vigorous growth observed',
    },
    {
      month: 'September-October',
      stage: 'Boll Development & Filling',
      activity: 'Monitor for boll rot; control pests; manage irrigation',
      temperature: '25-28°C',
      rainfall: '50-100 mm',
      irrigation: 'Reduce irrigation frequency; ensure good drainage',
      pestControl: 'Monitor for bollworm, spiny bollworm, leafcurl virus',
      notes: 'Boll maturity in 35-50 days depending on variety',
    },
    {
      month: 'October-November',
      stage: 'Boll Maturity & Opening',
      activity: 'Stop irrigation 2-3 weeks before harvest; pick mature bolls',
      temperature: '20-25°C',
      rainfall: '0-25 mm',
      yield: '15-25 quintals/ha lint @ 35-40% ginning outturn',
      notes: 'Pick 3-4 times at 7-10 day intervals',
    },
    {
      month: 'November-December',
      stage: 'Harvesting & Ginning',
      activity: 'Complete picking; clean and dry cotton; gin and bale',
      temperature: '18-24°C',
      yield: '15-25 quintals/ha cotton lint',
      notes: 'Store in moisture-proof containers',
    },
  ],

  /* ================= SUGARCANE ================= */
  sugarcane: [
    {
      month: 'November-December',
      stage: 'Land Preparation',
      activity: 'Deep ploughing (30 cm); incorporate crop residue; create furrows 75-90 cm apart',
      temperature: '18-24°C',
      rainfall: '0-50 mm',
      soilPrep: 'Well-drained clay loam; pH 6.0-8.0',
      notes: 'Prepare 2-3 weeks before planting',
    },
    {
      month: 'December-January',
      stage: 'Planting',
      activity: 'Plant setts (40-50 months cane @ 50,000 setts/ha); treat with Trichoderma',
      temperature: '18-22°C',
      rainfall: '25-50 mm',
      seedVariety: 'CoS8386, CoS96014 @ 50,000 setts/ha (25 tons/ha)',
      irrigation: 'Immediate irrigation after planting',
      fertilizer: 'FYM 20 tons/ha; P 60 kg/ha; K 60 kg/ha',
      soilPrep: 'Setts depth 2-3 cm; cover with organic matter',
    },
    {
      month: 'January-March',
      stage: 'Germination & Early Growth',
      activity: 'Maintain moisture; remove dead setts; mulching',
      temperature: '20-26°C',
      rainfall: '50-100 mm',
      irrigation: 'Frequent light irrigation; every 10-12 days',
      pestControl: 'Monitor for shoot borers, early shoot stage',
      notes: 'Germination takes 20-25 days',
    },
    {
      month: 'March-May',
      stage: 'Tillering',
      activity: 'Apply 1st split of N; heavy earthing up; weed control',
      temperature: '26-32°C',
      rainfall: '50-150 mm',
      irrigation: '2-3 irrigations during dry period',
      fertilizer: 'Urea 100 kg/ha in 2-3 splits (total 100 kg N/ha)',
      pestControl: 'Monitor for top borers using pheromone traps',
      notes: 'Earthing up at 90 and 180 DAS',
    },
    {
      month: 'May-July',
      stage: 'Grand Growth Period',
      activity: 'Regular irrigation; heavy weeding; apply N fertilizer',
      temperature: '28-32°C',
      rainfall: '200-300 mm (monsoon)',
      irrigation: 'Reduce during monsoon; ensure drainage',
      fertilizer: 'Urea 50 kg/ha; K 60 kg/ha in this period',
      pestControl: 'Monitor for root rot, ratoon diseases during heavy rainfall',
      notes: 'Critical period for cane development',
    },
    {
      month: 'July-September',
      stage: 'Vegetative to Mature Transition',
      activity: 'Control weeds; reduce N application; monitor pests',
      temperature: '25-30°C',
      rainfall: '150-200 mm',
      irrigation: 'Maintain adequate moisture without waterlogging',
      fertilizer: 'Stop N; apply K if deficiency symptoms observed',
      pestControl: 'Continue monitoring for pests; spray fungicide if needed',
      notes: 'Mature cane development begins',
    },
    {
      month: 'September-November',
      stage: 'Maturity & Ripening',
      activity: 'Withhold water to promote sugar accumulation',
      temperature: '18-24°C',
      rainfall: '0-50 mm',
      irrigation: 'Stop irrigation 30 days before harvest',
      notes: 'Sugar content peaks after maturity',
    },
    {
      month: 'November-February',
      stage: 'Harvesting',
      activity: 'Harvest at 12-14 months; cut at ground level; remove leaves',
      temperature: '14-22°C',
      yield: '70-80 tons/ha cane; ~10 tons/ha sugar',
      notes: 'Crush within 24 hours of harvest for better juice quality',
    },
  ],

  /* ================= MILLET ================= */
  millet: [
    {
      month: 'May-June',
      stage: 'Land Preparation & Sowing',
      activity: '2-3 ploughings; create 45 cm rows; sow @ 4-5 kg/ha',
      temperature: '25-30°C',
      rainfall: '100-150 mm',
      seedVariety: 'Rajendra, ICMH2 @ 4-5 kg/ha',
      fertilizer: 'FYM 5 tons/ha; DAP 40 kg/ha',
      soilPrep: 'Well-drained; loamy soil preferred',
    },
    {
      month: 'June-July',
      stage: 'Seedling & Thinning',
      activity: 'Thin to 10-15 cm spacing; light weeding',
      temperature: '25-30°C',
      rainfall: '75-150 mm',
      irrigation: 'Light irrigation if dry spell',
      fertilizer: 'Urea 30 kg/ha at 20-25 DAS',
      notes: 'Millet tolerates dry conditions well',
    },
    {
      month: 'July-August',
      stage: 'Vegetative Growth',
      activity: 'Maintain weed-free field; monitor for pests',
      temperature: '28-32°C',
      rainfall: '150-200 mm',
      irrigation: 'No irrigation required in monsoon; drain excess water',
      pestControl: 'Watch for armyworm, shoot fly',
      notes: 'Low input requirement; drought tolerant',
    },
    {
      month: 'August-September',
      stage: 'Heading & Flowering',
      activity: 'Panicle emergence; final weed control',
      temperature: '26-30°C',
      rainfall: '100-150 mm',
      notes: 'Avoid water stress during this critical stage',
    },
    {
      month: 'September-October',
      stage: 'Grain Filling & Maturity',
      activity: 'Monitor for diseases; harvest at physiological maturity',
      temperature: '22-28°C',
      rainfall: '25-75 mm',
      yield: '15-25 quintals/ha grain; 50-70 quintals/ha fodder',
      notes: 'Millet is highly nutritious, drought resistant',
    },
  ],

  /* ================= PULSES (General) ================= */
  pulses: [
    {
      month: 'September-October',
      stage: 'Land Preparation',
      activity: '2 ploughings; incorporate residue; create 30 cm rows',
      temperature: '25-30°C',
      rainfall: '50-100 mm',
      soilPrep: 'Well-drained; pH 6.5-7.5 preferred',
      notes: 'Prepare 2-3 weeks before sowing',
    },
    {
      month: 'October-November',
      stage: 'Sowing',
      activity: 'Sow @ 60-80 kg/ha; treat seed with Rhizobium culture',
      temperature: '20-25°C',
      seedVariety: 'Gram: ICCV96029, Moong: SML668 @ 15-20 kg/ha',
      fertilizer: 'P 40-50 kg/ha; K 20 kg/ha; no N needed (legume)',
      irrigation: 'Germination irrigation immediately after sowing',
    },
    {
      month: 'November-December',
      stage: 'Establishment & Early Growth',
      activity: 'Light weeding; monitor for diseases',
      temperature: '15-22°C',
      rainfall: '25-50 mm',
      irrigation: 'First irrigation at 40-50 DAS if winter is dry',
      pestControl: 'Monitor for shoot fly, aphids',
      notes: 'Pulses are low input crops',
    },
    {
      month: 'December-January',
      stage: 'Vegetative to Flowering',
      activity: 'Final weeding; avoid water stress; monitor pests',
      temperature: '12-18°C',
      rainfall: '10-25 mm',
      irrigation: 'Second irrigation at flowering if needed',
      pestControl: 'Spray for pod borer (Helicoverpa) if threshold crossed',
      notes: 'Critical period for pod formation',
    },
    {
      month: 'January-March',
      stage: 'Flowering & Pod Filling',
      activity: 'Prevent water stress; control pests; avoid overspreading',
      temperature: '15-25°C',
      rainfall: '0-50 mm',
      irrigation: 'Maintain moisture without waterlogging',
      pestControl: 'Continue monitoring; use pheromone traps',
      yield: '20-25 quintals/ha gram; 15-20 quintals/ha moong',
    },
    {
      month: 'March-April',
      stage: 'Maturity & Harvesting',
      activity: 'Harvest at pod browning; thresh and clean',
      temperature: '25-30°C',
      yield: '20-25 quintals/ha',
      notes: 'Store in cool, dry place; moisture <12%',
    },
  ],

  /* ================= GROUNDNUT ================= */
  groundnut: [
    {
      month: 'May-June',
      stage: 'Land Preparation & Sowing',
      activity: '3 ploughings; create 60 cm rows; sow @ 40 kg/ha',
      temperature: '25-30°C',
      rainfall: '75-150 mm',
      seedVariety: 'TG1, TMVG, TAG24 @ 60-75 kg/ha (kernel)',
      fertilizer: 'FYM 10 tons/ha; Gypsum 500 kg/ha; DAP 40 kg/ha',
      soilPrep: 'Light, well-drained sandy loam; pH 6.0-7.5',
    },
    {
      month: 'June-July',
      stage: 'Seedling & Thinning',
      activity: 'Thin to 15-20 cm spacing; light irrigation',
      temperature: '26-30°C',
      rainfall: '100-150 mm',
      irrigation: 'First irrigation at 20-30 DAS',
      fertilizer: 'Urea 30 kg/ha at 30 DAS',
      notes: 'Gypsum critical for pod development',
    },
    {
      month: 'July-August',
      stage: 'Vegetative Growth',
      activity: 'Frequent weeding; apply potash fertilizer',
      temperature: '28-32°C',
      rainfall: '150-200 mm',
      irrigation: '2nd irrigation at 45-50 DAS',
      fertilizer: 'Potash 40 kg/ha; repeat gypsum application if needed',
      notes: 'Groundnut needs Calcium (Gypsum) for kernel development',
    },
    {
      month: 'August-September',
      stage: 'Flowering & Pegging',
      activity: 'Critical stage; ensure adequate moisture & Gypsum',
      temperature: '28-30°C',
      rainfall: '100-150 mm',
      irrigation: '3rd irrigation at 60-65 DAS (critical)',
      fertilizer: 'No more N; focus on K and Gypsum',
      pestControl: 'Monitor for thrips, leaf miner, rosette virus',
      notes: 'Pegging: flower pedicel elongates & enters soil for pod development',
    },
    {
      month: 'September-October',
      stage: 'Pod Development & Filling',
      activity: 'Maintain moisture; avoid water stress',
      temperature: '25-28°C',
      rainfall: '50-100 mm',
      irrigation: '4th irrigation at 80-85 DAS',
      notes: 'Pod development takes 40-50 days',
    },
    {
      month: 'October-November',
      stage: 'Maturity & Harvesting',
      activity: 'Harvest when pods are fully mature (110-120 DAS)',
      temperature: '20-25°C',
      yield: '30-35 quintals/ha nuts; ~8-10 quintals/ha oil',
      notes: 'Cure for 2-3 weeks in sun; remove from field quickly',
    },
  ],

  /* ================= SOYBEAN ================= */
  soybean: [
    {
      month: 'May-June',
      stage: 'Land Preparation & Sowing',
      activity: '2-3 ploughings; sow @ 75 kg/ha in 45 cm rows',
      temperature: '25-30°C',
      rainfall: '100-150 mm',
      seedVariety: 'JS9570, JS30-81 @ 75 kg/ha',
      fertilizer: 'FYM 5 tons/ha; Inoculant; DAP 40 kg/ha',
      soilPrep: 'Well-drained; pH 6.0-7.5',
    },
    {
      month: 'June-July',
      stage: 'Seedling & Vegetative Growth',
      activity: 'Thin to 10-12 cm spacing; light weeding',
      temperature: '25-30°C',
      rainfall: '100-150 mm',
      irrigation: 'Light irrigation if dry',
      fertilizer: 'No additional N (nitrogen-fixing legume)',
      notes: 'Soybean fixes its own nitrogen through nodulation',
    },
    {
      month: 'July-August',
      stage: 'Vegetative to Flowering',
      activity: 'Maintain weed-free field; frequent weeding',
      temperature: '28-32°C',
      rainfall: '150-200 mm',
      irrigation: 'Ensure moisture without waterlogging',
      pestControl: 'Monitor for leaf-eating caterpillars, stem flies',
      notes: '2-3 weedings required',
    },
    {
      month: 'August-September',
      stage: 'Flowering & Pod Setting',
      activity: 'Critical moisture stage; avoid water stress',
      temperature: '26-30°C',
      rainfall: '100-150 mm',
      irrigation: 'Maintain soil moisture (no irrigation in monsoon)',
      pestControl: 'Monitor for pod borers, hemipterans',
      notes: 'Flowers appear at 35-45 DAS',
    },
    {
      month: 'September-October',
      stage: 'Pod Filling & Maturity',
      activity: 'Monitor for diseases; prepare for harvest',
      temperature: '22-28°C',
      rainfall: '25-75 mm',
      yield: '15-20 quintals/ha grain; 4-5 tons/ha biomass',
      notes: 'Maturity in 100-120 days from sowing',
    },
  ],

  /* ================= COFFEE ================= */
  coffee: [
    {
      month: 'May-June',
      stage: 'Flowering Preparation',
      activity: 'Reduce irrigation; ensure good drainage; apply nutrients',
      temperature: '20-25°C',
      rainfall: '100-150 mm (Blossom showers)',
      fertilizer: 'N:P:K = 100:50:100 kg/ha annual application',
      notes: 'Critical showers trigger flowering',
    },
    {
      month: 'June-July',
      stage: 'Flowering',
      activity: 'Monitor plant health; regulate shade; apply fungicide for leaf blotch',
      temperature: '20-25°C',
      rainfall: '150-200 mm',
      pestControl: 'Monitor for shot-hole borer, scale, whitefly',
      notes: 'Flowering lasts 4-6 weeks; fragrant white flowers',
    },
    {
      month: 'July-August',
      stage: 'Early Fruit Development',
      activity: 'Maintain moisture; control weeds; apply micronutrients',
      temperature: '20-25°C',
      rainfall: '150-200 mm',
      irrigation: 'No additional irrigation during monsoon',
      fertilizer: 'Potash 100 kg/ha for better quality; micronutrients',
    },
    {
      month: 'August-September',
      stage: 'Fruit Development & Expansion',
      activity: 'Shade regulation (40-50%); weed control; pest monitoring',
      temperature: '18-24°C',
      rainfall: '150-200 mm',
      pestControl: 'Monitor for berry borer (coffee borer), fungal diseases',
      notes: 'Berry borer causes significant loss; use pheromone traps',
    },
    {
      month: 'September-November',
      stage: 'Fruit Maturity & Ripening',
      activity: 'Monitor ripeness progression; prepare harvesting equipment',
      temperature: '18-24°C',
      rainfall: '50-100 mm',
      notes: 'Berries change from green → yellow → red → dark red (mature)',
    },
    {
      month: 'November-January',
      stage: 'Harvesting',
      activity: 'Selectively pick ripe berries; dry to 11-12% moisture',
      temperature: '15-20°C',
      yield: '2-3 tons/ha dried coffee @ 12% moisture',
      notes: 'Processing: wet process (washed) or dry process (sun-dried)',
    },
    {
      month: 'January-March',
      stage: 'Post-Harvest & Processing',
      activity: 'Winnow, sort, grade; prepare for export/market',
      temperature: '18-24°C',
      notes: 'Specialty coffee commands premium prices',
    },
  ],
};
